name: CI/CD Pipeline
on:
  push:
    branches:
      - ready/test

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/grandshipper"
        SCRIPT_BEFORE_REQUIRED: true
        SCRIPT_AFTER_REQUIRED: true
        
        # ECR Login
        SCRIPT_BEFORE: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        
        SCRIPT_AFTER: |
          echo $RSYNC_STDOUT
          ls -al
          cd /grandshipper

          # Build and push
          docker build -t grandshipper-test:local .
          docker tag grandshipper-test:local 024848460115.dkr.ecr.us-east-1.amazonaws.com/grandshipper-test:local
          docker push 024848460115.dkr.ecr.us-east-1.amazonaws.com/grandshipper-test:local



          

          

          
          

          

          