name: AWS EC2 CI

on:
  push:
    branches:
      - main

jobs:
  laravel:
    name: Continuous Integration
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker Compose Installation
        run: |
          docker-compose --version

      - name: Build and run Docker container
        run: |
          sudo docker-compose build app
          sudo docker-compose up -d

      - name: Install Composer dependencies
        run: sudo docker-compose exec app composer install --no-interaction --optimize-autoloader

      - name: Deploy to EC2
        run: |
            sudo mkdir -p /var/www/public 
            sudo cp -r * /var/www/public

      - name: Give permission
        run: |
          sudo chown -R www-data:www-data /var/www/public
          sudo chmod -R 775 /var/www/public
          sudo chmod -R 775 /var/www/public/storage
          sudo chmod -R 775 /var/www/public/bootstrap/cache
