name: CI/CD Pipeline
on:
  push:
    branches:
      - ready/test

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/grandshipper"
        SCRIPT_BEFORE: |
          mkdir -p /grandshipper
          whoami
          ls -al
        
        SCRIPT_AFTER: |
          mkdir -p .env/
          whoami
          ls -al
          echo $RSYNC_STDOUT
