name: AWS EC2 CI

on:
  push:
    branches:
      - main

jobs:
  laravel:
    name: Continuous Integration
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove old containers
        run: |
          sudo docker stop laravel-app laravel-nginx || true
          sudo docker rm laravel-app laravel-nginx || true

      - name: Build and run new Docker container
        run: |
          sudo docker-compose build app
          sudo docker-compose up -d

      - name: Install Composer dependencies
        run: sudo docker-compose exec app composer install --no-interaction --optimize-autoloader

      - name: Make directory and copy entire folders
        run: |
          sudo mkdir -p /var/www/html
          sudo cp -r * /var/www/html

      - name: Set File Permissions
        run: |
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 775 /var/www/html/public
          sudo chmod -R 775 /var/www/html/storage
          sudo chmod -R 775 /var/www/html/bootstrap/cache

      - name: Down Docker container in actions-runner
        run: sudo docker-compose down

      - name: Build and run Docker
        working-directory: /var/www/html
        run: |
          sudo docker-compose build app
          sudo docker-compose up -d
